### ISSUE TITLE
Show Name of RootviewController

### ISSUE THREAD

**Issue by ogezue** [anzfactory/ANZBreadcrumbsNavigationController#2]
I need to display the name of the rootview controller. Currently the breadcrumps get visible when there are two controllers on the stack. 
Would it be possible to have an option to configure this? ([X] showRootOnStart)

<img width="239" alt="bildschirmfoto 2018-07-16 um 16 29 21" src="https://user-images.githubusercontent.com/2361031/42764360-b78070b0-8915-11e8-8eb8-4dbd105193e0.png">
root is on stack but not in breadcrumps

<img width="239" alt="bildschirmfoto 2018-07-16 um 16 29 17" src="https://user-images.githubusercontent.com/2361031/42764362-ba1febd4-8915-11e8-95e1-12e4fc66c7a3.png">
2 controllers are on stack and in breadcrumps

**Comment by anzfactory** [comment]
Added new property. `isRootDisplayed` -> [v0.3.0](https://github.com/anzfactory/ANZBreadcrumbsNavigationController/releases/tag/0.3.0)

![rootbreadcrumbs](https://user-images.githubusercontent.com/4214784/42878372-cc040642-8ac7-11e8-824b-7379b4c64820.gif)

**Comment by ogezue** [comment]
Wow - Thank you!
