### ISSUE TITLE
Need iOS 9 Support

### ISSUE THREAD

**Issue by PawanAhire** [anzfactory/ANZBreadcrumbsNavigationController#4]
Hi, I found this repository very useful for my Application, but I need to give support to iOS 9. So is it possible?

**Comment by anzfactory** [comment]
support iOS 9.

try it!! -> [v0.5.0](https://github.com/anzfactory/ANZBreadcrumbsNavigationController/releases/tag/0.5.0)

**Comment by PawanAhire** [comment]
Hi,
Thanks for the quick response, v0.5.0 is working for the iOS 9, but the
tableview is hiding behind the breadcrumb


Regards,
Pawan.

**Comment by anzfactory** [comment]
ummm 🤔 

can not work automatic adjustment iOS 9 or 10. 
so refs [example](https://github.com/anzfactory/ANZBreadcrumbsNavigationController/blob/1b8ca706336c433bef001a41890329e4b03f9382/Example/ANZBreadcrumbsNavigationController/TableViewController.swift#L25-L29).

**Comment by PawanAhire** [comment]
Hi,
I referred the example, and it works fine.


Thank you,
Pawan.

**Comment by PawanAhire** [comment]
Hi,
Is it possible to hide the breadcrumb for the first time, means on first
screen?

**Comment by PawanAhire** [comment]
Hi,
One more question i.e. how should I use this framework in the application
which uses the xib's instead of storyboard?
 I went through your example but it uses the navigation controller in
storyboard.

Waiting for your reply.



Regards,
Pawan.

On Jan 25, 2019 6:15 PM, "Pawan Ahire" <ahire.pawan@gmail.com> wrote:

Hi,
Is it possible to hide the breadcrumb for the first time, means on first
screen?

**Comment by anzfactory** [comment]
> Is it possible to hide the breadcrumb for the first time, means on first
screen?

it is impossible. sorry.

> xib .. ??

use `ANZBreadcrumbsNavigationController` instead of `UINavigationController`

```swift
let vc = UIViewController(nibName: "FirstViewController", bundle: nil)
let nav = ANZBreadcrumbsNavigationController(rootViewController: vc)

// if needed
let config = ANZBreadcrumbsNavigationConfig()
config.height = 60.0
config.backgroundColor = .blue
nav.config = config
```

**Comment by PawanAhire** [comment]
Thanks for your help, I done with the above.


Only need to hide breadcrumb for the first screen.

**Comment by anzfactory** [comment]
[v0.6.0 release](https://github.com/anzfactory/ANZBreadcrumbsNavigationController/releases/tag/0.6.0)

add `isAutoHidden` property

```swift
let vc = UIViewController(nibName: "FirstViewController", bundle: nil)
let nav = ANZBreadcrumbsNavigationController(rootViewController: vc)

let config = ANZBreadcrumbsNavigationConfig()
config.isAutoHidden = true

// 👇if needed

class ViewController: UIViewController {
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // detect breadcrumbs view visibility
        NotificationCenter.default.addObserver(self, selector: #selector(type(of: self).didShowBreadcrumbsViewNotified(_:)), name: .ANZBreadcrumbsDidShowBreadcrumbsView, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(type(of: self).didHideBreadcrumbsViewNotified(_:)), name: .ANZBreadcrumbsDidHideBreadcrumbsView, object: nil)
        
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NotificationCenter.default.removeObserver(self)
    }

    private func didShowBreadcrumbsViewNotified(_ notification: Notification) {
        
        guard let config = notification.object as? ANZBreadcrumbsNavigationConfig else {
            return
        }
        
        if #available(iOS 11.0, *) { } else {
            var inset = self.tableView.contentInset
            var top = UIApplication.shared.statusBarFrame.height + config.height
            if let navigationBar = self.navigationController?.navigationBar {
                top += navigationBar.frame.height
            }
            inset.top = top
            self.tableView.contentInset = inset
        }
    }
    
    private func didHideBreadcrumbsViewNotified(_ notification: Notification) {
        
        if #available(iOS 11.0, *) { } else {
            var inset = self.tableView.contentInset
            var top = UIApplication.shared.statusBarFrame.height
            if let navigationBar = self.navigationController?.navigationBar {
                top += navigationBar.frame.height
            }
            inset.top = top
            self.tableView.contentInset = inset
        }
    }
}
```

refs. launch Example -> User Defined Runtime Attr Ver.

**Comment by PawanAhire** [comment]
Hi,
Thanks for your help, I will do the same and will inform you the output.



Regards,
Pawan

**Comment by PawanAhire** [comment]
Hi,
Did the same as you mentioned, but it's not working for me.

Also I am trying to set the close button to the top left corner of each
view controller. And on close action user should taken back to MainVC

It's working for the iOS 11+ devices, but crashing for below iOS 11 devices.



Regards,
Pawan.

**Comment by anzfactory** [comment]
oh...
sorry. :pray: 
I'll look it up.

**Comment by anzfactory** [comment]
release v0.6.1.
how is this?

**Comment by PawanAhire** [comment]
Hi,
Checked v0.6.0 and it's working fine for me, will check the next version
tomorrow and will get back to you.

Thank you so much for your help and support.

Actually I need to show home icon for the first screen instead of string
table1, and onwards the selected cells title text in table to the
breadcrumb.


Regards,
Pawan.

**Comment by PawanAhire** [comment]
"*The main purpose of using this library is for nested picker, to show the
parent child hierarchy and to select the multiple objects below the
breadcrumb as a oval with cross button to deselect the object.*"


The main purpose of using this library is for nested picker, to show the
parent child hierarchy and to select the multiple objects and show the
selected objects below the breadcrumb as a oval with cross button to
deselect the object.
